"""Generate the Avalonia and CSS exports from branding/tokens/tokens.json (stdlib only)."""
import json
import pathlib
import re
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[1]
tokens = json.loads((ROOT / 'branding/tokens/tokens.json').read_text(encoding='utf-8'))

def pascal(value):
    return value[0].upper() + value[1:]

def css_name(value):
    return re.sub(r'(?<!^)(?=[A-Z])', '-', value).lower()

def color(value):
    if value.startswith('rgba('):
        r, g, b, a = map(float, value[5:-1].split(','))
        return f'#{round(a * 255):02X}{int(r):02X}{int(g):02X}{int(b):02X}'
    return value

aliases = {
    'SessionBackground': 'appBackground', 'SessionSidebar': 'panel',
    'SessionSurface': 'panel', 'SessionForeground': 'textPrimary',
    'SessionMuted': 'textMuted', 'SessionBorder': 'line',
    'SessionAccent': 'brand', 'SessionAccentText': 'onBrand',
    'SessionSelection': 'brandSoft', 'SessionError': 'danger',
}
lines = ['<!-- Generated by scripts/Generate-BrandTheme.py; edit tokens.json. -->',
    '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    '  <ResourceDictionary.ThemeDictionaries>']
for theme, colors in tokens['color'].items():
    lines.append(f'    <ResourceDictionary x:Key="{pascal(theme)}">')
    for name, value in colors.items():
        if name == 'shadow':
            continue
        lines.append(f'      <SolidColorBrush x:Key="{pascal(name)}Brush">{color(value)}</SolidColorBrush>')
    for name, source in aliases.items():
        lines.append(f'      <SolidColorBrush x:Key="{name}">{color(colors[source])}</SolidColorBrush>')
    # Fluent's built-in input/check/radio focus states share the same primary color.
    for name in ('SystemAccentColor', 'SystemAccentColorDark1', 'SystemAccentColorDark2',
                 'SystemAccentColorLight1', 'SystemAccentColorLight2'):
        lines.append(f'      <Color x:Key="{name}">{colors["brand"]}</Color>')
    lines.append('    </ResourceDictionary>')
lines.append('  </ResourceDictionary.ThemeDictionaries>')
lines.append('  <FontFamily x:Key="AppFont">avares://Sessions.App/Assets/Fonts#Manrope, Segoe UI</FontFamily>')
for group, prefix, kind in [('spacing','Space','x:Double'), ('size','Size','x:Double'), ('radius','Radius','CornerRadius')]:
    for name, value in tokens[group].items():
        lines.append(f'  <{kind} x:Key="{prefix}{pascal(name)}">{value}</{kind}>')
for name, value in tokens['typography']['scale'].items():
    key = 'Font' + pascal(name)
    for suffix, kind, v in [('Size','x:Double',value['size']), ('Weight','FontWeight',value['weight']),
            ('LineHeight','x:Double',round(value['size'] * value['lineHeight'], 2))]:
        lines.append(f'  <{kind} x:Key="{key}{suffix}">{v}</{kind}>')
for kind, resources in tokens['avalonia'].items():
    for key, value in resources.items():
        lines.append(f'  <{kind} x:Key="{key}">{escape(str(value))}</{kind}>')
lines.append('</ResourceDictionary>')
output = '\n'.join(lines) + '\n'
for path in ('branding/tokens/Theme.axaml', 'src/Sessions.App/Styles/BrandTheme.axaml'):
    (ROOT / path).write_text(output, encoding='utf-8')

css = ['/* Generated by scripts/Generate-BrandTheme.py. The host selects the OS theme. */']
for theme, colors in tokens['color'].items():
    css.append(f'[data-theme="{theme}"] {{')
    css.extend(f'  --{css_name(name)}: {value};' for name, value in colors.items())
    css.append('}')
css.append(':root {')
css.append(f'  --font-family: {tokens["typography"]["family"]};')
for group, prefix in [('spacing','space'),('size','size'),('radius','radius')]:
    css.extend(f'  --{prefix}-{css_name(name)}: {value}px;' for name, value in tokens[group].items())
for name, values in tokens['typography']['scale'].items():
    for prop, value in values.items():
        unit = 'px' if prop == 'size' else ''
        css.append(f'  --font-{css_name(name)}-{css_name(prop)}: {value}{unit};')
css.extend(f'  --motion-{css_name(name)}: {value};' for name, value in tokens['motion'].items())
css.append('}')
(ROOT / 'branding/tokens/tokens.css').write_text('\n'.join(css) + '\n', encoding='utf-8')
print('Generated Avalonia and CSS token exports.')
